name: Rust CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Cargo and Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Run Cargo Tests
        run: cargo test --all --verbose

      - name: Set up Bun
        run: curl -fsSL https://bun.sh/install | bash

      - name: Add Bun to PATH
        run: echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Playwright Browsers
        run: bunx playwright install

      - name: Install deps in tests
        run: cd tests && bun install

      - name: Start Server in Background
        run: cargo run &

      - name: Wait for Server to Start
        run: sleep 5

      - name: Run Playwright Tests
        run: cd tests && bunx playwright test

      - name: Kill Background Processes
        run: pkill cargo || true
